# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4719888d-6e64-4125-9664-08f6bc6f8ea6";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/00ecc8f7-6ee0-401e-bb51-3604f45e9ea5";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4719888d-6e64-4125-9664-08f6bc6f8ea6";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/4719888d-6e64-4125-9664-08f6bc6f8ea6";
    fsType = "btrfs";
    options = ["subvol=@log"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4719888d-6e64-4125-9664-08f6bc6f8ea6";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6130-6F70";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
