# Placeholder hardware configuration for bootstrapping the elitebook host.
# Replace with the real file generated by `nixos-generate-config` after installing.
{lib, ...}: {
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  fileSystems."/" = {
    device = lib.mkDefault "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = lib.mkDefault "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
    fsType = "btrfs";
  };

  fileSystems."/nix/store" = {
    device = lib.mkDefault "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = lib.mkDefault "/dev/disk/by-uuid/0000-0000";
    fsType = "vfat";
  };
}
