# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/80d8bc66-a6f7-4744-9caf-c481ab383906";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/80d8bc66-a6f7-4744-9caf-c481ab383906";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-uuid/80d8bc66-a6f7-4744-9caf-c481ab383906";
    fsType = "btrfs";
    options = ["subvol=@nix-store"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0F46-FD86";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
