# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e0bfca2c-e6a9-44c7-bc15-c3cd7a567689";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-uuid/e0bfca2c-e6a9-44c7-bc15-c3cd7a567689";
    fsType = "btrfs";
    options = ["subvol=@nix-store"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e0bfca2c-e6a9-44c7-bc15-c3cd7a567689";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A30E-47AB";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
